definitions:
  model.ErrorMessage:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  model.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      id:
        type: string
      login:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /user:
    get:
      consumes:
      - application/json
      description: Get a list of users per page
      parameters:
      - description: page number (0 or more)
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorMessage'
      summary: User list
      tags:
      - User
swagger: "2.0"
