
services:
  rest:
    build:
      context: .
      dockerfile: _deploy/Dockerfile
      target: minerva_go_rest
    environment:
      - GIN_MODE=release
      - MINERVA_LOG_LEVEL=debug
      - MINERVA_USER_HOST=user:9010
      - MINERVA_SESSION_HOST=session:9011
      - MINERVA_PRODUCTS_HOST=products:9012
      - MINERVA_TENANT_HOST=tenant:9013
    ports:
      - 9000:9000
    depends_on:
      user:
        condition: service_started
      session:
        condition: service_started
      products:
        condition: service_started
    labels:
      logging: "promtail"
      logging_jobname: "rest"

  user:
    build:
      context: .
      dockerfile: _deploy/Dockerfile
      target: minerva_go_user
    environment:
      - MINERVA_LOG_LEVEL=debug
      - DATABASE_SERVICE_SERVER=mariadb:3306
      - DATABASE_SERVICE_USER=mysql
      - DATABASE_SERVICE_PASSWORD=mysql
      - DATABASE_SERVICE_DBNAME=minerva
      - BROKER_SERVICE_SERVER=rabbitmq:5672
      - BROKER_SERVICE_USER=rabbitmq
      - BROKER_SERVICE_PASSWORD=rabbitmq
    ports:
      - 9010:9010
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    labels:
      logging: "promtail"
      logging_jobname: "user"

  session:
    build:
      context: .
      dockerfile: _deploy/Dockerfile
      target: minerva_go_session
    environment:
      - MINERVA_LOG_LEVEL=debug
      - DATABASE_SERVICE_SERVER=mariadb:3306
      - DATABASE_SERVICE_USER=mysql
      - DATABASE_SERVICE_PASSWORD=mysql
      - DATABASE_SERVICE_DBNAME=minerva
      - BROKER_SERVICE_SERVER=rabbitmq:5672
      - BROKER_SERVICE_USER=rabbitmq
      - BROKER_SERVICE_PASSWORD=rabbitmq
    ports:
      - 9011:9011
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    labels:
      logging: "promtail"
      logging_jobname: "session"

  products:
    build:
      context: .
      dockerfile: _deploy/Dockerfile
      target: minerva_go_products
    environment:
      - MINERVA_LOG_LEVEL=debug
      - DATABASE_SERVICE_SERVER=mariadb:3306
      - DATABASE_SERVICE_USER=mysql
      - DATABASE_SERVICE_PASSWORD=mysql
      - DATABASE_SERVICE_DBNAME=minerva
      - BROKER_SERVICE_SERVER=rabbitmq:5672
      - BROKER_SERVICE_USER=rabbitmq
      - BROKER_SERVICE_PASSWORD=rabbitmq
    ports:
      - 9012:9012
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    labels:
      logging: "promtail"
      logging_jobname: "products"

  tenant:
    build:
      context: .
      dockerfile: _deploy/Dockerfile
      target: minerva_go_tenant
    environment:
      - MINERVA_LOG_LEVEL=debug
      - DATABASE_SERVICE_SERVER=mariadb:3306
      - DATABASE_SERVICE_USER=mysql
      - DATABASE_SERVICE_PASSWORD=mysql
      - DATABASE_SERVICE_DBNAME=minerva
      - BROKER_SERVICE_SERVER=rabbitmq:5672
      - BROKER_SERVICE_USER=rabbitmq
      - BROKER_SERVICE_PASSWORD=rabbitmq
    ports:
      - 9013:9013
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    labels:
      logging: "promtail"
      logging_jobname: "tenant"

        
# =========================================
        
  mariadb:
    image: mariadb:11.3
    environment:
      - MARIADB_ROOT_PASSWORD=mysql
      - MARIADB_DATABASE=minerva
      - MARIADB_USER=mysql
      - MARIADB_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=minerva
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    ports:
      - 3306:3306
    volumes:
      - ./_deploy/compose-data/database:/var/lib/mysql
    healthcheck:
      interval: 30s
      retries: 50
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s
    labels:
      logging: "promtail"
      logging_jobname: "mariadb"
    
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    volumes:
      - ./_deploy/compose-config/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./_deploy/compose-config/rabbitmq/10-defaults.conf:/etc/rabbitmq/conf.d/10-defaults.conf:ro
      - ./_deploy/compose-data/broker:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 50
    labels:
      logging: "promtail"
      logging_jobname: "rabbitmq"

# =========================================

  loki:
    image: grafana/loki:2.9.7
    ports:
      - 3100:3100
      - 9096:9096
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.7
    volumes:
      - ./_deploy/compose-config/promtail/promtail-config.yml:/etc/promtail/promtail-config.yaml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yaml

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    volumes:
      - ./_deploy/compose-config/grafana/ds.yml:/etc/grafana/provisioning/datasources/ds.yaml:ro
      - ./_deploy/compose-config/grafana/dashboard_examples/logs_dashboard.json:/var/lib/grafana/dashboards/minerva/logs.json:ro
      - ./_deploy/compose-config/grafana/dashboard_examples/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml:ro

