---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  template:
    metadata:
      name: mariadb
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb-container
          image: mariadb:11.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-pv
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mariadb-credentials
      volumes:
        - name: mariadb-pv
          persistentVolumeClaim:
            claimName: mariadb-pvc
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
---
