---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-container
          image: rabbitmq:3.13-management-alpine
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-pv
            - mountPath: /etc/rabbitmq/
              name: rabbitmq-plugin-config
            - mountPath: /etc/rabbitmq/conf.d
              name: rabbitmq-config
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
            - containerPort: 15692
              name: vhost
          envFrom:
            - secretRef:
                name: rabbitmq-credentials
      volumes:
        - name: rabbitmq-pv
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
        - name: rabbitmq-plugin-config
          configMap:
            name: rabbitmq-plugins
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
---
