---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: minerva-credentials
data:
  DATABASE_SERVICE_USER: bXlzcWw=
  DATABASE_SERVICE_PASSWORD: bXlzcWw=
  DATABASE_SERVICE_DBNAME: bWluZXJ2YQ==
  BROKER_SERVICE_USER: cmFiYml0bXE=
  BROKER_SERVICE_PASSWORD: cmFiYml0bXE=
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mariadb-credentials
data:
  MARIADB_ROOT_PASSWORD: bXlzcWw=
  MARIADB_DATABASE: bWluZXJ2YQ==
  MARIADB_USER: bXlzcWw=
  MARIADB_PASSWORD: bXlzcWw=
  MYSQL_ROOT_PASSWORD: bXlzcWw=
  MYSQL_DATABASE: bWluZXJ2YQ==
  MYSQL_USER: bXlzcWw=
  MYSQL_PASSWORD: bXlzcWw=
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rabbitmq-credentials
data:
  RABBITMQ_DEFAULT_USER: cmFiYml0bXE=
  RABBITMQ_DEFAULT_PASS: cmFiYml0bXE=
---

