basePath: /api/v1
definitions:
  model.Company:
    properties:
      companyName:
        type: string
      createdAt:
        type: string
      id:
        type: string
      slug:
        type: string
      tradingName:
        type: string
      updatedAt:
        type: string
    type: object
  model.Product:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      price:
        type: number
      unit:
        type: string
      updatedAt:
        type: string
    type: object
  model.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      login:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
  schema.BooleanResponse:
    properties:
      value:
        type: boolean
    type: object
  schema.ErrorMessage:
    properties:
      details:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  schema.NewCompany:
    properties:
      companyName:
        maxLength: 255
        minLength: 3
        type: string
      slug:
        maxLength: 30
        minLength: 3
        type: string
      tradingName:
        maxLength: 255
        minLength: 3
        type: string
    required:
    - companyName
    - slug
    - tradingName
    type: object
  schema.NewProduct:
    properties:
      description:
        type: string
      price:
        type: number
      unit:
        type: string
    required:
    - description
    - price
    - unit
    type: object
  schema.NewUser:
    properties:
      email:
        type: string
      login:
        maxLength: 25
        minLength: 5
        type: string
      name:
        maxLength: 100
        type: string
      password:
        minLength: 8
        type: string
    required:
    - login
    - name
    - password
    type: object
  schema.UpdatedCompany:
    properties:
      companyName:
        maxLength: 255
        type: string
      slug:
        maxLength: 30
        type: string
      tradingName:
        maxLength: 255
        type: string
    type: object
info:
  contact:
    email: lucasvieira@protonmail.com
    name: Lucas S. Vieira
    url: https://luksamuk.codes
  description: Minerva System API (v1)
  license:
    name: MIT
    url: https://choosealicense.com/licenses/mit/
  title: Minerva System API
  version: "1.0"
paths:
  /{company}/products:
    get:
      consumes:
      - application/json
      description: Get a list of products per page
      parameters:
      - description: company UUID
        in: path
        name: company
        required: true
        type: string
      - description: page number (0 or more)
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Product'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
      summary: Products list
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Create a new product
      parameters:
      - description: company UUID
        in: path
        name: company
        required: true
        type: string
      - description: new product data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schema.NewProduct'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
      summary: Create product
      tags:
      - Products
  /{company}/products/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a specific product
      parameters:
      - description: company UUID
        in: path
        name: company
        required: true
        type: string
      - description: product UUID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: deleted successfully
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
      summary: Delete product
      tags:
      - Products
    get:
      consumes:
      - application/json
      description: Get data of a specific product
      parameters:
      - description: company UUID
        in: path
        name: company
        required: true
        type: string
      - description: product UUID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
      summary: Get product
      tags:
      - Products
  /{company}/users:
    get:
      consumes:
      - application/json
      description: Get a list of users per page
      parameters:
      - description: company UUID
        in: path
        name: company
        required: true
        type: string
      - description: page number (0 or more)
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
      summary: User list
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: company UUID
        in: path
        name: company
        required: true
        type: string
      - description: new user data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schema.NewUser'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
      summary: Create user
      tags:
      - User
  /{company}/users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a specific user
      parameters:
      - description: company UUID
        in: path
        name: company
        required: true
        type: string
      - description: user UUID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: deleted successfully
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
      summary: Delete user
      tags:
      - User
    get:
      consumes:
      - application/json
      description: Get data of a specific user
      parameters:
      - description: company UUID
        in: path
        name: company
        required: true
        type: string
      - description: user UUID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
      summary: Get user
      tags:
      - User
  /companies:
    get:
      consumes:
      - application/json
      description: Get a list of companies per page
      parameters:
      - description: page number (0 or more)
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Company'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
      summary: Company list
      tags:
      - Tenant
    post:
      consumes:
      - application/json
      description: Create a new company
      parameters:
      - description: new company data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schema.NewCompany'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Company'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
      summary: Create company
      tags:
      - Tenant
  /companies/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a specific company (disabling is a soft-delete).
      parameters:
      - description: company UUID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: disabled successfully
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
      summary: Disable company
      tags:
      - Tenant
    get:
      consumes:
      - application/json
      description: Get data of a specific company by id
      parameters:
      - description: company UUID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Company'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
      summary: Get company
      tags:
      - Tenant
    put:
      consumes:
      - application/json
      description: Update information of a specific company
      parameters:
      - description: company update data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schema.UpdatedCompany'
      - description: company UUID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Company'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
      summary: Update company
      tags:
      - Tenant
  /companies/by-slug/{slug}:
    get:
      consumes:
      - application/json
      description: Get data of a specific company by unique identifier (slug)
      parameters:
      - description: company slug
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Company'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
      summary: Get company by slug
      tags:
      - Tenant
  /companies/exists:
    get:
      consumes:
      - application/json
      description: Check whether a specific company exists
      parameters:
      - description: company UUID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.BooleanResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorMessage'
      summary: Check company existence
      tags:
      - Tenant
swagger: "2.0"
