{
 "title": "Logs dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Log tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "REST HTTP Logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{container=~\"^minerva-go-.*$\"} |= ``"
    }
   ]
  },
  {
   "title": "REST service",
   "type": "table",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{job=\"rest\"}"
    }
   ]
  },
  {
   "title": "USER service",
   "type": "table",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{job=\"user\"} |= ``"
    }
   ]
  },
  {
   "title": "PRODUCTS service",
   "type": "table",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{job=\"products\"} |= ``"
    }
   ]
  },
  {
   "title": "TENANT service",
   "type": "table",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{job=\"tenant\"} |= ``"
    }
   ]
  }
 ]
}