---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minerva-rest
spec:
  template:
    metadata:
      name: rest
      labels:
        app: rest
    spec:
      containers:
        - name: minerva-rest-container
          image: luksamuk/minerva_go_rest:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: GIN_MODE
              value: "release"
            - name: MINERVA_LOG_LEVEL
              value: "info"
          envFrom:
            - configMapRef:
                name: minerva-services-dns
          resources:
            requests:
              cpu: 50m
  replicas: 3
  selector:
    matchLabels:
      app: rest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minerva-user
spec:
  template:
    metadata:
      name: user
      labels:
        app: user
    spec:
      containers:
        - name: minerva-user-container
          image: luksamuk/minerva_go_user:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9010
          env:
            - name: MINERVA_LOG_LEVEL
              value: "info"
          envFrom:
            - configMapRef:
                name: minerva-services-dns
            - secretRef:
                name: minerva-credentials
          resources:
            requests:
              cpu: 50m
  replicas: 2
  selector:
    matchLabels:
      app: user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minerva-products
spec:
  template:
    metadata:
      name: products
      labels:
        app: products
    spec:
      containers:
        - name: minerva-products-container
          image: luksamuk/minerva_go_products:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9012
          env:
            - name: MINERVA_LOG_LEVEL
              value: "info"
          envFrom:
            - configMapRef:
                name: minerva-services-dns
            - secretRef:
                name: minerva-credentials
          resources:
            requests:
              cpu: 50m
  replicas: 2
  selector:
    matchLabels:
      app: products
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minerva-tenant
spec:
  template:
    metadata:
      name: tenant
      labels:
        app: tenant
    spec:
      containers:
        - name: minerva-tenant-container
          image: luksamuk/minerva_go_tenant:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9013
          env:
            - name: MINERVA_LOG_LEVEL
              value: "info"
          envFrom:
            - configMapRef:
                name: minerva-services-dns
            - secretRef:
                name: minerva-credentials
          resources:
            requests:
              cpu: 50m
  replicas: 2
  selector:
    matchLabels:
      app: tenant
---
