---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
    - name: mysql
      port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
    - name: management
      port: 15672
    - name: vhost
      port: 15692
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
    - name: elastic
      port: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: ClusterIP
  selector:
    app: kibana
  ports:
    - name: http
      port: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: rest
spec:
  type: LoadBalancer
  selector:
    app: rest
  ports:
    - name: rest
      port: 9000
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - name: grpc
      port: 9010
---
apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  type: ClusterIP
  selector:
    app: products
  ports:
    - name: grpc
      port: 9012
---
