---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: minerva-rest
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: minerva-user
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: products
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: minerva-products
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tenant
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: minerva-tenant
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
---
