---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  type: ClusterIP
  selector:
    app: phpmyadmin
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  template:
    metadata:
      name: phpmyadmin
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin-container
          image: phpmyadmin:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: "mariadb"
            - name: PMA_PORT
              value: "3306"
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin

